### ISSUE TITLE
Hinzufügen personalisierter Pläne für einige Fakultäten funktioniert nicht mehr nach Semesterstart

### ISSUE THREAD

**Issue by l3d00m** [SplusEins/SplusEins#449]
Bei den Fakultäten E und I ist es nicht mehr möglich, neue personalisierte Pläne anzulegen:

1. Personalisierten Plan anlegen für E oder I
2. Es werden keine Kurse geladen:
![image](https://user-images.githubusercontent.com/12055376/99877282-260c6980-2bfd-11eb-853c-32215de38d3f.png)

## Grund 

Die Kurse werden geladen, indem sämtliche Lectures zu Semesteranfang geladen werden und diese dann einfach auf Duplikate gefiltert werden: https://github.com/SplusEins/SplusEins/blob/0058132f46fa3acac04607900d738c0b0a7a8bbf/web/components/custom-timetable-dialog.vue#L213-L218

Wie allerdings zB [hier in sked](https://stundenplan.ostfalia.de/e/semester/E-EIT(iP)-AT-Sem5.html) zu sehen, zeigen die Fakultäten E und I die bereits vergangenen Wochen nicht mehr an, weshalb dann 5 Wochen nach Semesterstart das Erstellen neuer Pläne nicht mehr funktioniert, da dann für diese Wochen keine Lectures mehr geladen werden können.

## Schneller Fix/Workaround
Es wäre möglich, die `SEMESTER_WEEK_1` oben einfach durch die aktuelle zu ersetzen.

## Ausführlicher Fix
Am schönsten wäre es, die Pläne sämtlicher Wochen zu laden. Das passiert im Backend eh schon, es wird nur aktuell zusätzlich nochmal auf die ausgewählte Woche gefiltert, um nicht alle gleichzeitig zurückzugeben:
https://github.com/SplusEins/SplusEins/blob/9fed9b68846ea312d622bcd7cae2f28b7d9eb4d8/server/lib/SkedParser.ts#L196-L198
Man müsste dann einen neuen API-Endpoint hinzufügen, der ähnlich wie der bisherige funktioniert, mit dem Unterschied, dass er zum Einen die Funktion oben ohne den gezeigten Filter aufruft und dann backend-seitig die "unique lectures" herausfiltert. Dieses Filtern passiert aktuell komplett im Frontend.

Ich würde letzteres bevorzugen und im Zuge dessen auch mal die `parseSked`-Funktionen optimieren, indem ich deren Result ebenfalls cache. Da ich dafür aber ne Weile brauchen werden, würde ich eventuell erst den Quickfix implementieren, da das ein ziemlich nerviger Bug ist.

**Comment by schneefux** [comment]
Ja, das ist eine Altlast. Aus splus konnte man damals nur wochenweise laden.
Beide Fixes sind gut 👍
