### ISSUE TITLE
Vollständige Anzeige von Dozenten Namen

### ISSUE THREAD

**Issue by jarikmarwede** [SplusEins/SplusEins#567]
Es wäre hilfreich, wenn man die vollen Namen von Dozierenden sehen könnte und nicht nur die Abkürzungen. Vielleicht mithilfe eines Tooltips, zumindest am PC.

**Comment by l3d00m** [comment]
Hi, danke für dein Feedback! Leider ist das aus datenschutzrechtlichen Gründen nicht möglich und das ist auch der Grund, warum die offiziellen Stundenpläne der Ostfalia passwort-geschützt sind.

**Comment by jarikmarwede** [comment]
Danke für die Erklärung. Das macht Sinn
