### ISSUE TITLE
Personalisierter Plan verschwindet aus Seitenleiste

### ISSUE THREAD

**Issue by jarikmarwede** [SplusEins/SplusEins#570]
Wenn ich momentan einen personalisierten Plan im Bearbeitungsmodus ohne Änderungen speichere, verschwindet bei mir der Eintrag in der Seitenleiste. Nach einem Neuladen der Seite, taucht der Eintrag wieder in der Seitenleiste auf.

Vorher:
![image](https://user-images.githubusercontent.com/33765260/221180944-c9b3f128-3cc9-4b23-babb-55c4e0ff5371.png)

Nachher:
![image](https://user-images.githubusercontent.com/33765260/221180867-7dbe999a-61de-4472-83ec-5bc55e83a76d.png)

Error Log:
```
da32cb6.modern.js:1 <no-ssr> has been deprecated and will be removed in Nuxt 3, please use <client-only> instead
render @ da32cb6.modern.js:1
spluseins.de/:1 Autofocus processing was blocked because a document already has a focused element.
6b05fbe.modern.js:2 Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/plan?id=i_sye_po18_3_ss23&id=i_soe_po18_4_ss23&id=i_alle_wpf_ss23&id=i_soe_po18_3_ss23&course=waWuD&course=0r42u&course=81BW4&course=Ls4Yx&course=agYCM&course=8hsEB&course=bK0RO&course=AD1BW&name=test&v=1".
    at It (https://spluseins.de/_nuxt/6b05fbe.modern.js:2:132403)
    at qt.confirmTransition (https://spluseins.de/_nuxt/6b05fbe.modern.js:2:135492)
    at qt.transitionTo (https://spluseins.de/_nuxt/6b05fbe.modern.js:2:134817)
    at e.replace (https://spluseins.de/_nuxt/6b05fbe.modern.js:2:138033)
    at https://spluseins.de/_nuxt/6b05fbe.modern.js:2:142818
    at new Promise (<anonymous>)
    at ee.replace (https://spluseins.de/_nuxt/6b05fbe.modern.js:2:142781)
    at f.save (https://spluseins.de/_nuxt/a96ecde.modern.js:1:16311)
    at click (https://spluseins.de/_nuxt/a96ecde.modern.js:1:17474)
    at Ue (https://spluseins.de/_nuxt/6b05fbe.modern.js:2:17908)
It @ 6b05fbe.modern.js:2
qt.confirmTransition @ 6b05fbe.modern.js:2
qt.transitionTo @ 6b05fbe.modern.js:2
e.replace @ 6b05fbe.modern.js:2
(anonymous) @ 6b05fbe.modern.js:2
ee.replace @ 6b05fbe.modern.js:2
save @ a96ecde.modern.js:1
click @ a96ecde.modern.js:1
Ue @ 6b05fbe.modern.js:2
n @ 6b05fbe.modern.js:2
c._wrapper @ 6b05fbe.modern.js:2
```

**Comment by l3d00m** [comment]
Kann ich reproduzieren, danke. 

Ich bin schon seit einer Weile durch mit dem Bachelor und nicht mehr an der Ostfalia, weshalb ich mich nur noch nebenbei um SplusEins kümmere und nur dafür sorge, dass die Pläne einmal im Semester aktualisiert werden. Deshalb wird der Bug wahrscheinlich erstmal eine Zeit bestehen bleiben, bis sich wer anderes findet, der sich drum kümmern möchte.

Wenn du Lust hast, selber was zu fixen, kannst du das sehr gerne tun! Ich würd mich sehr über PRs freuen und kann da auch etwas bei helfen. 

Ansonsten kannst du sehr gerne weiterhin Issues eröffnen, dann findet sich bestimmt irgendwann mal wer, der sich drum kümmert!

**Comment by jarikmarwede** [comment]
In dem Fall erstmal danke, dass du dich noch kümmerst. SplusEins ist echt super hilfreich.
Ich habe mal eine PR geöffnet #572
