### ISSUE TITLE
Mensaplan Wolfsburg

### ISSUE THREAD

**Issue by felixsch28** [SplusEins/SplusEins#884]
Es wäre super, wenn der Mensaplan von Wolfsburg hinzugefügt wird.
Ob dafür eine extra Navigation hinzugefügt wird oder man unter "Mensa" ein Dropdown oder ein Tabreiter hat ist dabei egal.

Vielen Dank im Voraus :)

**Comment by felixsch28** [comment]
Mensa ID: 112

**Comment by l3d00m** [comment]
Hallo, wir sind leider alle nicht mehr so aktiv, sodass wir keine Zeit für neue Features haben. Wenn du Lust hast, kannst du das aber gerne selber entwickeln. Ich helfe auch gern bei Fragen. Ich denke, dass ist nur mittelviel Aufwand, weil es das Mensa-System ja schon gibt.

**Comment by l3d00m** [comment]
Einfacher ist wahrscheinlicher ein neuer Reiter, schöner ist vielleicht der dropdown. Aber das kannst du gerne selber entscheiden.

**Comment by felixsch28** [comment]
Hi. @l3d00m beim setup einer lokalen Instanz kam es bei mir zu kleineren Fehlern. Wäre es möglich, dass du mir dabei einmal helfen könntest?

**Comment by l3d00m** [comment]
Gerne! Entweder hier, oder du schickst mir deinen Discord/Matrix whatever Nutzernamen per Mail an github@kxlion.de und ich adde dich da

**Comment by felixsch28** [comment]
Hi danke für die schnelle Antwort. Auf Discord heiße ich "felixs".
